version: "3.8"

services:
  # Backend API service (development mode)
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: backend-base
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=thelastcentaur
      - SECRET_KEY=dev-secret-key
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ../:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend service (development mode)
  web:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://localhost:8001
      - HOST=0.0.0.0

  # Database service
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thelastcentaur
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
