"""add missing columns to gameinstance

Revision ID: 4ae73c4d51eb
Revises: 8984e6f54e1e
Create Date: 2025-02-25 23:53:55.443430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae73c4d51eb'
down_revision: Union[str, None] = '8984e6f54e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if enum type exists before creating it
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gamestatus') THEN CREATE TYPE gamestatus AS ENUM ('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED'); END IF; END $$;")
    
    # Add columns with default values for existing rows
    op.add_column('gameinstance', sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='gamestatus'), server_default='ACTIVE', nullable=False))
    op.add_column('gameinstance', sa.Column('max_players', sa.Integer(), server_default='1', nullable=False))
    op.add_column('gameinstance', sa.Column('current_players', sa.Integer(), server_default='1', nullable=False))
    op.add_column('gameinstance', sa.Column('description', sa.String(length=500), nullable=True))
    
    # Fix foreign key constraint - check if index exists first
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_tile_game_instance_id') THEN DROP INDEX ix_tile_game_instance_id; END IF; END $$;")
    
    # Check if foreign key exists before creating it
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tile_game_instance_id_fkey') THEN ALTER TABLE tile ADD CONSTRAINT tile_game_instance_id_fkey FOREIGN KEY (game_instance_id) REFERENCES gameinstance(id); END IF; END $$;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tile_game_instance_id_fkey', 'tile', type_='foreignkey')
    op.create_index('ix_tile_game_instance_id', 'tile', ['game_instance_id'], unique=False)
    op.drop_column('gameinstance', 'description')
    op.drop_column('gameinstance', 'current_players')
    op.drop_column('gameinstance', 'max_players')
    op.drop_column('gameinstance', 'status')
    
    # We don't drop the enum type in downgrade as it might be used elsewhere
    # ### end Alembic commands ###
